mask is now a required input, to avoid error-prone brain/background thresholding step

diff --git a/preproc/smooth_susan b/preproc/smooth_susan
--- a/preproc/smooth_susan
+++ b/preproc/smooth_susan
@@ -2,9 +2,9 @@
 #
 #  Based on the smoothing used in FEAT 6.0.
 
-if [ $# -lt 3 ]; then
-    echo "Usage:   smooth_susan [-f hpf_sigma] [-vk] input fwhm output"
-    echo "Example: smooth_susan -f 32 loc_1 4.0 loc_1_sm"
+if [ $# -lt 4 ]; then
+    echo "Usage:   smooth_susan [-f hpf_sigma] [-vk] input mask fwhm output"
+    echo "Example: smooth_susan -f 32 loc_1 mask 4.0 loc_1_sm"
     echo
     echo "Options:"
     echo "-f"
@@ -37,8 +37,9 @@ done
 shift $((OPTIND-1))
 
 func=$1
-smooth=$2
-output=$3
+mask=$2
+smooth=$3
+output=$4
 
 name=$(basename $func .nii.gz)
 parent=$(dirname $func)
@@ -49,32 +50,31 @@ done
 sdir=$parent/$dirname
 mkdir -p $sdir
 
+# create mask
+if [ $(imtest $mask) = 0 ]; then
+    echo "Error: mask does not exist: $mask"
+    exit 1
+fi
+    
 fslmaths $func $sdir/prefiltered_func_data -odt float
 pd=$(pwd)
 cd $sdir
 funcdata=prefiltered_func_data
 
-# image statistics
-int_2_98=$(fslstats $funcdata -p 2 -p 98)
-int2=$(echo $int_2_98 | awk '{print $1}')
-int98=$(echo $int_2_98 | awk '{print $2}')
-# using the default brain/background threshold in FEAT (10%)
-intensity_threshold=$(python -c "print $int2 + 0.1 * ($int98 - $int2)")
-
-# create mask
-fslmaths $funcdata -thr $intensity_threshold -Tmin -bin mask -odt char
+imcp $mask mask
 median_intensity=$(fslstats $funcdata -k mask -p 50)
-fslmaths mask -dilF mask
 fslmaths $funcdata -mas mask prefiltered_func_data_thresh
 funcdata=prefiltered_func_data_thresh
 
 # spatial filtering
 smoothsigma=$(python -c "print $smooth/2.355")
-susan_int=$(python -c "print ($median_intensity - $int2) * 0.75")
+
+# the 0.1 percentile within mask is similar to using the 2nd
+# percentile over the whole image, but better controlled
+int1=$(fslstats $funcdata -k mask -p 0.1)
+susan_int=$(python -c "print ($median_intensity - $int1) * 0.75")
 if [ $verbose == 1 ]; then
-    echo "p2: $int2"
-    echo "p98: $int98"
-    echo "mask threshold: $intensity_threshold"
+    echo "int1: $int1"
     echo "median: $median_intensity"
     echo "susan int: $susan_int"
     echo "smooth sigma: $smoothsigma"
