throw an error when BATCHDIR does not exist

diff --git a/utils/rlaunch b/utils/rlaunch
--- a/utils/rlaunch
+++ b/utils/rlaunch
@@ -107,7 +107,10 @@ else
 fi
 
 if [ -z "$BATCHDIR" ]; then
-    export BATCHDIR=.
+    export BATCHDIR=$PWD
+elif [ ! -d "$BATCHDIR" ]; then
+    echo "Error: BATCHDIR does not exist: $BATCHDIR"
+    exit 1
 fi
 
 # determine file to write commands to
diff --git a/utils/slaunch b/utils/slaunch
--- a/utils/slaunch
+++ b/utils/slaunch
@@ -101,7 +101,10 @@ shift 2
 nos=$(echo $nos | sed "s/:/ /g")
 
 if [ -z "$BATCHDIR" ]; then
-    export BATCHDIR=.
+    export BATCHDIR=$PWD
+elif [ ! -d "$BATCHDIR" ]; then
+    echo "Error: BATCHDIR does not exist: $BATCHDIR"
+    exit 1
 fi
 
 # determine file to write commands to
